//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.league = new HashSet<league>();
            this.leagueparticipants = new HashSet<leagueparticipants>();
            this.squad = new HashSet<squad>();
        }
    
        public int userId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public bool gender { get; set; }
        public string cellPhone { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string country { get; set; }
        public string closestCity { get; set; }
        public int UserGroup_idUserGroup { get; set; }
        public string image { get; set; }
    
        public virtual ICollection<league> league { get; set; }
        public virtual ICollection<leagueparticipants> leagueparticipants { get; set; }
        public virtual ICollection<squad> squad { get; set; }
        public virtual usergroup usergroup { get; set; }
    }
}
